# Generated by Django 3.2.12 on 2023-06-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_fantasy', '0002_userregistry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_country', models.CharField(max_length=100)),
                ('team_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer_fantasy.userregistry')),
            ],
        ),
        migrations.CreateModel(
            name='PlayersRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_firstname', models.CharField(max_length=100)),
                ('player_lastname', models.CharField(max_length=100)),
                ('player_age', models.IntegerField(default=0)),
                ('player_country', models.CharField(max_length=100)),
                ('player_value', models.IntegerField(default=0)),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer_fantasy.teams')),
            ],
        ),
    ]
