# Generated by Django 3.2.12 on 2023-06-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_fantasy', '0003_playersregistry_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='team_budget',
            field=models.IntegerField(default=0),
        ),
    ]
